### ISSUE TITLE
🚀 - ng-add improvements 

### ISSUE THREAD

**Issue by vladimirpotekhin** [TinkoffCreditSystems/taiga-ui#1014]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

taiga-schematics
1. add @angular/cdk dep with addon-table and addon-mobile

### Description

we should instal some peer deps on ng add
see https://github.com/TinkoffCreditSystems/taiga-ui/issues/979#issuecomment-971258663

**Comment by thekiba** [comment]
When I started installing taiga via ng add, a cool wizard appeared to select various options.

But in one of the paragraphs there was a choice of packages that can be supplied additionally.

![telegram-cloud-photo-size-2-5258353436183869774-y](https://user-images.githubusercontent.com/1910515/143428974-592942ee-414b-43c1-9a7e-7d92d9fb88d5.jpg)

And here I ran into a problem that I did not understand what some of these packages were doing, what their installation would give me, and where you can read more about them.

I think it would be great to add a brief description of why each of the packages may be needed, and perhaps add a link where you can read a more detailed description about each package.

**Comment by Teebo** [comment]
Maybe prepend Taiga styles in angular.json for variables overriding?

Maybe do

targetOptions.styles = [...taigaStyles, ...styles];

[here](https://github.com/TinkoffCreditSystems/taiga-ui/blob/c32b4247002e7f6b2693f1c727d6c7b3a2aa98aa/projects/taiga-schematics/schematics/ng-add/steps/add-taiga-styles.ts#L32)?

**Comment by waterplea** [comment]
We should also include that info on add-ons on the Getting started page
