### ISSUE TITLE
🐞 - multiselect valuecontent right aligned

### ISSUE THREAD

**Issue by taramara** [TinkoffCreditSystems/taiga-ui#1019]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/multi-select/API?tuiMode=null&valueContent$=1

### Description

After the recent change, valueContent of multi-select has a wrapper with `justify-content: flex-end;` It makes everything in the valueContent right aligned.

In the docu it looks like this:
![image](https://user-images.githubusercontent.com/94632611/142455085-808a8ce6-43fb-4a11-b3d2-3fb29012a500.png)

This happened after the recent bug fix (https://github.com/TinkoffCreditSystems/taiga-ui/pull/982) in version 2.23.0.

I have categorized this as a bug but if it is intentional, please take it as a request to change it back to how it was before. Thank you!

### Angular version

12.1.3

### Taiga UI version

2.23.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Sorry about that, yes, it's a big and fix is coming next Monday.

**Comment by taramara** [comment]
Awesome thank you for the fast response and your work! A big fan of taiga ui!

**Comment by waterplea** [comment]
Resolved in 2.24.0 ;)
