### ISSUE TITLE
[BUG] the UI is freezes on page https://taiga-ui.dev/tui-tabs

### ISSUE THREAD

**Issue by AnteaterKit** [TinkoffCreditSystems/taiga-ui#102]
Hi!
When I try to open the page https://taiga-ui.dev/tui-tabs the application becomes broken, UI on holding.

**Comment by MarsiBarsi** [comment]
Hey 👋

Thank you for your interest in our library :) 

It is okay for me. Please, provide some information about your system and browser with versions

**Comment by AnteaterKit** [comment]
Hi
macOS Catalina 10.15.7 (19H2)
Chrome Version 87.0.4280.141 (Official Build) (x86_64)

<img width="1440" alt="Screenshot 2021-01-16 at 12 51 17" src="https://user-images.githubusercontent.com/5115677/104808792-95679980-57f9-11eb-8142-70bf45e348af.png">
<img width="1440" alt="Screenshot 2021-01-16 at 12 53 56" src="https://user-images.githubusercontent.com/5115677/104808859-03ac5c00-57fa-11eb-85e1-fddd9731b666.png">

I try to open this page in incognito mode and it's work fine. 
In default chrome mode I try to clear the site data, but it does not help.
I think that I start to use this site in the first versions, something cached.

**Comment by AnteaterKit** [comment]
i try localhost
<img width="1436" alt="Screenshot 2021-01-16 at 13 10 07" src="https://user-images.githubusercontent.com/5115677/104809468-80d9d000-57fe-11eb-981c-f00a36c50f5c.png">

**Comment by AnteaterKit** [comment]
i solve my problem. it's chrome extension  Music Saver Version 1.5.0. for vk.
It's very interesting for angular, because in my home project, my users write me about strange bugs related with different extensions.
May be some extensions try to manipulate DOM of app and angular changeDetection default going crazy? What do you think?

**Comment by AnteaterKit** [comment]
I think it need to pay attention. 
In my main options i develop for enterprise solutions and it's not problem.
But chrome in real world have a lot of extension like skyeng, yandex music and other useful extensions.
Do you think how to protect against this problem and what the cause this behavior?

**Comment by waterplea** [comment]
I noticed there's an issue with resize observer that watches over tabs that should go into «More» drop-down. Perhaps the root cause is the same. Once I fix it I'll ping you to give it another shot.

**Comment by 200051393** [comment]
https://user-images.githubusercontent.com/11832552/104365178-bc3b7c80-5528-11eb-8d16-c481ec250024.png

**Comment by 200051393** [comment]
https://user-images.githubusercontent.com/11832552/104365178-bc3b7c80-5528-11eb-8d16-c481ec250024.png

**Comment by waterplea** [comment]
@AnteaterKit can you try it now please? I've fixed the issue I had, maybe it fixes yours too.

**Comment by AnteaterKit** [comment]
Hi! Thank you.
I try to open tabs **without** extension Music Saver Version 1.5.0. for vk - its ok.
In next time a try **with extension** and i got this https://drive.google.com/file/d/1HU-ubwP2xG6v8_Ci9bwrPRrmbfiAuL7z/view?usp=sharing

**Comment by waterplea** [comment]
Harlem Shake extension 😁 Installed it and able to reproduce. Will look into it later.

**Comment by WynieCronje** [comment]
I see the **TuiUnderlineComponent** causes a lot of JS execution during idle :) . (debug tools > Javascript Profiler) in Chrome.

I haven't investigated the code in depth. But surely we can do something to reduce idle execution 😄

**Comment by waterplea** [comment]
Yeah, it runs `requestAnimationFrame` to sync position with current element in case of resize or other situations where underline position and active tab positions change, but it does so outside of `NgZone` and it doesn't really do much. Looks like that extension is causing DOM mutations that trigger endless mutation observer callback loop.

**Comment by waterplea** [comment]
Figured it out. This extension inserts following style:
```
.hidden {
  display: none;
}
```
This breaks our internal encapsulated code. That's a pretty bold move on their part. I have let the extension author know. I've renamed this class since it's the only place we use it, but overall I don't think we should try to guard ourselves from careless extension developers.
