### ISSUE TITLE
🚀 - TUI_VALIDATION_ERRORS token should be able to work with observables

### ISSUE THREAD

**Issue by EricPoul** [TinkoffCreditSystems/taiga-ui#1051]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

I want to change the value of validation errors on language observable emits like I can do on TUI_NOTHING_FOUND_MESSAGE for example.

**Comment by ArtemeeSenin** [comment]
It would also be great if it would be possible to pass [errorsDict] to <tui-field-error> if you need different messages for the same error type

**Comment by waterplea** [comment]
> It would also be great if it would be possible to pass [errorsDict] to if you need different messages for the same error type

You can always override this dictionary on any level if you need to change the message for the same error in particular place:
```ts
{
  provide: TUI_VALIDATION_ERRORS,
  deps: [[new SkipSelf(), TUI_VALIDATION_ERRORS],
  useFactory: errors => ({ ...errors, required: 'Different required message' }),
}
```
