### ISSUE TITLE
🚀 - Add a directive to process value before it is copied

### ISSUE THREAD

**Issue by Mahakon** [TinkoffCreditSystems/taiga-ui#1085]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

when user copy number it should be sanitized from thousand separator 

### Angular version

13.0.2

### Taiga UI version

2.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is more of a job for custom directive:
https://stackblitz.com/edit/taiga-copy-number

**Comment by waterplea** [comment]
Come to think of it, makes sense to add it to `@taiga-ui/cdk` 🤔 @Mahakon would like to contribute it?

**Comment by Mahakon** [comment]
@waterplea yes i will do it today)

**Comment by waterplea** [comment]
Cool, I've renamed it over at Stackblitz so it's pretty much copy-paste + demo page :)
