### ISSUE TITLE
Compile with Ivy

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#109]
Hi,

Thanks for this awesome library.  I haven't started fully using it yet but planning to.  I've just noticed the library is compiled against Angular 9 (https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/package.json#L57)  and enabling ivy on stack blitz (https://stackblitz.com/edit/taiga?file=tsconfig.json) results in a failed build.  Is there plans to upgrade to Angular 11 and support ivy in the near future?

**Comment by waterplea** [comment]
Hi @jonsamwell 
Thank you for your interest in our library! It is perfectly compatible with Ivy and Angular 11, I use it on my projects too. That issue is on the StackBlitz side:
https://github.com/stackblitz/core/issues/1364

**Comment by jonsamwell** [comment]
Great thanks!
