### ISSUE TITLE
🐞 - Incorrect display of the InputCardGrouped component in FF

### ISSUE THREAD

**Issue by RoodNick** [TinkoffCreditSystems/taiga-ui#1096]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-commerce

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-card-grouped

### Description

Placeholder of the InputCardGrouped component doesn't hide in FF by default as in other browsers. 
<img width="1155" alt="Снимок экрана 2021-12-11 в 12 49 38" src="https://user-images.githubusercontent.com/4251958/145672656-3c8a64ce-b712-48a7-9801-176659b530c5.png">

### Angular version

12.0.5

### Taiga UI version

2.26.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
firefox:

![image](https://user-images.githubusercontent.com/12021443/145720547-9b016c9c-70e0-4ac5-ac01-336076c58055.png)
