### ISSUE TITLE
🐞 - Dialog is not centered vertically anymore on mobiles

### ISSUE THREAD

**Issue by rvalitov** [TinkoffCreditSystems/taiga-ui#1128]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Description

After updating Taiga, I found out that dialogs have different vertical position now. In the past the dialogs were always centered vertically. Now I see that the dialogs are centered vertically only on desktop. On mobiles they are positioned to the bottom of the screen:
![image](https://user-images.githubusercontent.com/16267156/146760818-8ac29fbd-7736-427f-b4df-bb9825f361f3.png)

I used a test example from docs https://taiga-ui.dev/components/dialog
It looks like a breaking change for me. Is there a way to position the dialogs vertically now?

### Angular version

12.2.13

### Taiga UI version

2.27.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
They were always like that on mobiles. But the resolution from which it was considered a mobile has changed, sorry about that. @vladimirpotekhin how about we migrate everything to the media token so it's configurable? This way we can move it back to how everything was and only override it in the proprietary code.

**Comment by waterplea** [comment]
I think these are the only components that depend on CSS breakpoints rather than the token:

- InputCardGrouped
- Preview
- TableBar
- Dialog

**Comment by waterplea** [comment]
@rvalitov in version 2.28.0 you can now override this token to tell Taiga UI components what break point should be considered a mobile view so they adapt:
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/core/tokens/media.ts
Try setting mobile to 600 to make it behave the old way or go for even smaller values if you like.
