### ISSUE TITLE
[FEATURE] UI-Sidebar

### ISSUE THREAD

**Issue by WuglyakBolgoink** [TinkoffCreditSystems/taiga-ui#113]
# 🚀 Feature request

will be great to have the same component

https://fomantic-ui.com/modules/sidebar.html

**Comment by waterplea** [comment]
We have a generic sidebar directive, forgot to add it to demo portal :)

It's there now:
https://taiga-ui.dev/tui-sidebar

If you have some more concrete requests, feel free to open another issue!

**Comment by alex-jss** [comment]
@waterplea can you post an example implementation on stackblitz?

**Comment by waterplea** [comment]
@alex-jss fixed the link above. Same example on StackBlitz:
https://stackblitz.com/edit/angular-t1ndjr?file=src%2Fapp%2Fapp.module.ts

**Comment by alex-jss** [comment]
@waterplea Thanks for the example. Found it in the documentation too. Can you if an example of adaptation for a mobile phone with the inclusion of a header? For example, as you did on the documentation page.

**Comment by waterplea** [comment]
This is a low level directive. What you do with it is completely up to you. Just add header to it and style it with CSS :)
