### ISSUE TITLE
[BUG]  valueContent of Tui Select doesn't work with `0` as value

### ISSUE THREAD

**Issue by DPros** [TinkoffCreditSystems/taiga-ui#115]
# 🐞 [valueContent] of Tui Select doesn't work with `0` as value

### Reproduction

select "Option 0"
https://stackblitz.com/edit/taiga-starter-dgk5ua?file=src%2Fapp%2Fapp.component.html

### Expected behavior

[valueContent] for `0` value should work the same as for other numbers ("Option 0" and not "0")

### Versions

-   Windows 10
-   Browser chrome
-   Angular 11
-   Package taiga-ui@2.1.2

**Comment by waterplea** [comment]
Thank you for noticing this. We will release a new patch version today with fix for this and all other issues that were closed recently.
