### ISSUE TITLE
[FEATURE] Contextual button colors

### ISSUE THREAD

**Issue by fynnfeldpausch** [TinkoffCreditSystems/taiga-ui#123]
# 🚀 Feature request

### Is your feature request related to a problem?

We are in need of contextual buttons that indicate success or danger.

### Describe the solution you'd like

Buttons appearance mode should also support "Success" and "Error" and use the colors already defined in the current colors set.

### Additional context

![success](https://user-images.githubusercontent.com/1246913/105184726-f6f87280-5b2f-11eb-82c1-4a0d3384b03b.png)
![error](https://user-images.githubusercontent.com/1246913/105184729-f7910900-5b2f-11eb-97e5-dcd24af4a4a7.png)

**Comment by waterplea** [comment]
This can be achieved by custom buttons. Check out the last example:
https://taiga-ui.dev/tui-button#custom

Buttons, like many other components, use `tui-wrapper` component under the hood. It is responsible for displaying interactive state for different _Appearances_. You can extend it by adding your custom appearances and defining them in global styles, as shown in example.

I will cover that in Customization guide I plan to add this week.

**Comment by fynnfeldpausch** [comment]
Perfect, this solves my use case.
