### ISSUE TITLE
[BUG] Dialog close button missing

### ISSUE THREAD

**Issue by fynnfeldpausch** [TinkoffCreditSystems/taiga-ui#127]
# 🐞 Bug report

### Description

The close button for dialogs seems to be missing regardless of the settings of `closeable` input.

### Reproduction

* Head to https://taiga-ui.dev/tui-dialog-service/API?closeable=true
* Open the dialog
* Check if the close button is missing

### Expected behavior

A close button is shown in the corner of the dialog.

**Comment by fynnfeldpausch** [comment]
Sorry, I totally expected it to be in the corner of the dialog. Found it in the corner of the screen :-D

**Comment by jonsamwell** [comment]
I think perhaps the contrast of that close button isn't strong enough to catch the eye especially on large screens

**Comment by waterplea** [comment]
Thanks for raising it. I'll bring it up with designers to maybe come up with some different color.

**Comment by jonsamwell** [comment]
Probably not top priority as I guess this is themable?

**Comment by waterplea** [comment]
Actually, this particular button is custom styled ) but the whole dialog is easily customized. Will add it to the guide.
