### ISSUE TITLE
[BUG] Editor has Russian text

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#131]
# 🐞 Bug report

### Description

The editor has Russian text.

### Reproduction

https://stackblitz.com/edit/taiga-starter-dtl6lb

### Expected behavior

Create a Token to manipulate **Font** and **Code** values 

### Additional context

https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/addon-editor/components/toolbar/toolbar.component.ts#L95,L127

**Comment by waterplea** [comment]
Yes, sorry, it is an unfinished "experimental" package :)

**Comment by MarsiBarsi** [comment]
Fixed in your PR #155 
Thank you again!

**Comment by WynieCronje** [comment]
I just realized that this was resolved with the PR #155.

**Files:** 
https://github.com/TinkoffCreditSystems/taiga-ui/pull/155/files#diff-f67f9065b8fa56a818abc0e695bc845ef68dd4f8e484675c194a7f727adbf3e8

I hope this doesn't impact your current projects. @MarsiBarsi  @waterplea

**Comment by MarsiBarsi** [comment]
@WynieCronje yes, it is cool, I have reviewed the whole PR :)
We'll make i18n for this package after fixing some its bugs
