### ISSUE TITLE
[REFACTOR] Translate tests to english

### ISSUE THREAD

**Issue by fynnfeldpausch** [TinkoffCreditSystems/taiga-ui#141]
# 🚀 Refactoring request

### Is your feature request related to a problem?

I would like to contribute to the tests, but most of them are written in Russian.

### Describe the solution you'd like

Tests should be translated to english.

**Comment by MarsiBarsi** [comment]
All right, thanks, it is also one of our priorities to get rid of Russian language in our repo :)

If you see a test and understand what it does from code, feel free to translate it and we'll correct it on review if there are some problems ;)

**Comment by WynieCronje** [comment]
I translated some through Google Translate, and they still made sense.

Is it worth doing this once of for comments and tests? 

If so, I'll  be happy to help with this chore. (After my day job)

**Comment by waterplea** [comment]
@WynieCronje sure! We can correct it if we see a mistake on PR :)
