### ISSUE TITLE
[BUG] SVG XSS

### ISSUE THREAD

**Issue by mruknowme** [TinkoffCreditSystems/taiga-ui#143]
# 🐞 Bug report

### Description

SVG icons not rendering, throwing XSS warning and instead of icons printing `SafeValue must use [property]=binding:  (see https://g.co/ng/security#xss)` on the page.

What am I missing?

### Reproduction

**app.module.ts**
```typescript
// ...
providers: [
    {
      provide: Sanitizer,
      useClass: NgDompurifySanitizer,
    }
  ],
// ...
```

**my.component.ts**
```typescript
// ...
import { tuiIconPin, tuiIconCheckList } from '@taiga-ui/icons';
// ...
readonly mapIcon = tuiIconPin;
readonly lstIcon = tuiIconCheckList;
// ...
```

**my.component.html**
```html
<!-- ... -->
<tui-tabs>
      <button tuiTab
              type="button">
        <tui-svg [src]="mapIcon"
                 class="tui-space_right-2"></tui-svg>
        Maps
      </button>
      <button tuiTab
              type="button">
        <tui-svg [src]="lstIcon"
                 class="tui-space_right-2"></tui-svg>
        Settings
      </button>
    </tui-tabs>
<!-- ... -->
```

### Expected behavior

Rendered icons :) 

### Versions

-   OS: [e.g. iOS]
-   Browser: Chrome
-   Angular: 11
-   Taiga: 2.2.1

**Comment by MarsiBarsi** [comment]
Hey! 👋 

What versions of NgDompurify and Dompurify do you have?

**Comment by waterplea** [comment]
Able to reproduce. Thank you for reporting this!
