### ISSUE TITLE
[BUG] isFirefox util does not detect Firefox

### ISSUE THREAD

**Issue by MarsiBarsi** [TinkoffCreditSystems/taiga-ui#156]
it seems like some user agents have changed and now our `isFirefox` util function does not match modern Firefox

![image](https://user-images.githubusercontent.com/10106368/105877315-e3a64500-6010-11eb-9f79-cdca61769975.png)

**Comment by WynieCronje** [comment]
I saw something similar on this website. (https://netmarketshare.com/)

They mention new standards, and link to this repo: 
https://github.com/WICG/ua-client-hints

**Comment by WynieCronje** [comment]
Ignore my previous comment. It's going to be an issue in future :)

I did some checking. Seems like the UserAgent string for Firefox is Uppercase **F**, and included methods is case sensitive.

![image](https://user-images.githubusercontent.com/4537265/105991311-4bf63480-60ac-11eb-9776-af0b78500159.png)

Code in Repo: Will create a PR later
https://github.com/TinkoffCreditSystems/taiga-ui/blob/b35a89181cb59e6ae5f80a54d52ea266490152c1/projects/cdk/utils/browser/is-firefox.ts#L1

**Comment by WynieCronje** [comment]
![image](https://user-images.githubusercontent.com/4537265/106013196-e5c9db80-60c4-11eb-89c4-1bc1a54bf7a1.png)
