### ISSUE TITLE
Ionic-angular Compatibility. 

### ISSUE THREAD

**Issue by harrowmykel** [TinkoffCreditSystems/taiga-ui#161]
Hi, this is a really great project and I would like to implement it in future apps. 

What is the the current compatibility status for ionic-angular?

**Comment by waterplea** [comment]
Hello @harrowmykel. Thank you for your interest in our library! I have ported our StackBlitz starter to latest Angular + Ionic and it seems to be working fine:
https://stackblitz.com/edit/taiga-ui-ionic
Please let us know if you will face any particular issues using Taiga UI with Ionic
