### ISSUE TITLE
[FEATURE] Progress Bar / Ring

### ISSUE THREAD

**Issue by BreadBomb** [TinkoffCreditSystems/taiga-ui#162]
# 🚀 Feature request

### Describe the solution you'd like

There is no progress indicator like a progress bar or ring in this library. This is quite common in other libraries and should also be implemented in taiga-ui.

### Describe alternatives you've considered

The slider can be used with read only, but this is not realy a solution.

### Additional context

This is a good example:
https://ng.ant.design/components/progress/en

![image](https://user-images.githubusercontent.com/8608647/106104936-734c1080-6143-11eb-9285-b08b4c836550.png)

**Comment by MarsiBarsi** [comment]
Hey 👋

Yes, this is a good idea! Moreover, we have already had this component in our previous versions but deprecated it because it should be refactored. So, we'll make these both options of progress soon :)

**Comment by waterplea** [comment]
It should also support multiple levels, like progress bar of a video — whole bar, cached and current progress.

**Comment by rvalitov** [comment]
Does the ProgressCircle implements all of this?

**Comment by waterplea** [comment]
> Does the ProgressCircle implements all of this?

Seems like it 🙂 thanks for bumping this issue
