### ISSUE TITLE
[FEATURE] - Demo: Show all modules used in each example

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#166]
# 🚀 Feature request

### Is your feature request related to a problem?

If one quickly wants to reproduce a bug from the demo page. Or play around. Developers intend to copy and paste the HTML, TS, and Style content into  StackBlitz. 

Most of the time there are module error because other modules were used in the same example.

### Describe the solution you'd like

Would be nice to know all the modules involved in each example. This will help devs understand how modular the Taiga UI approach really is.

Or even better, a  StackBlitz for each example 😄 

### Additional context

Screenshot from Angular Material:
![image](https://user-images.githubusercontent.com/4537265/106236321-48c28c00-6205-11eb-8611-a4feb8441fc6.png)

**Comment by MarsiBarsi** [comment]
Cool, I'll do it in the coming days :)

**Comment by waterplea** [comment]
I've created a blanket issue for Open on StackBlitz problems:
#673
