### ISSUE TITLE
[BUG] Demo - fix issues mentioned on live session

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#180]
# 🐞 Bug report

#### Wrapper
No TS template:
https://youtu.be/JK0Fp7bQ52w?t=757

#### Icons
Wrong less file:
https://youtu.be/JK0Fp7bQ52w?t=1800

**Comment by MarsiBarsi** [comment]
Thank you! You are awesome!

**Comment by WynieCronje** [comment]
I'm busy fixing it. expect a PR soon 😄

**Comment by WynieCronje** [comment]
@MarsiBarsi nvm. See you already fixed it lol. You are 2 fast 😄
