### ISSUE TITLE
[BUG] - Demo - DarkMode bug.

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#184]
# 🐞 Bug report

### Description

My default gets changed to night mode (because of browser settings).

When I switch to day mode. Not all text is visible.

### Reproduction

Browser should be on dark mode.
[getting-started](https://taiga-ui.dev/getting-started)

Switch to light. The below happens:
![image](https://user-images.githubusercontent.com/4537265/106350129-39624200-62dc-11eb-8108-0e4bc1a8cda0.png)
Then
![image](https://user-images.githubusercontent.com/4537265/106350136-454e0400-62dc-11eb-88dd-aa5074ea9f47.png)

I did realize after investigation that this only happens when:

```ts
export const changeDetection = ChangeDetectionStrategy.OnPush;
```

### Versions

-   OS: Windows
-   Browser Chrome
-   Angular Demo

### Additional context
The below attribute on the links never changed:
![image](https://user-images.githubusercontent.com/4537265/106350226-c73e2d00-62dc-11eb-8e4b-a1da1270dc05.png)

**Comment by WynieCronje** [comment]
I was thinking. Since we have the CSS variables. Why not just override them on dark mode?
Is there really a need to change attributes and using different variables?

**Comment by waterplea** [comment]
Not everything is as simple as a var switch, sometimes you only want to change appearance of a particular component, not everything around it. And in case of inputs it is more than just a colour change.
