### ISSUE TITLE
[FEATURE] Demo: Sync the opened doc page and the navigation side panel

### ISSUE THREAD

**Issue by vadimk7** [TinkoffCreditSystems/taiga-ui#189]
# 🚀 Feature request

### Is your feature request related to a problem?

 
If one opens the given link to the doc page or search and chose some stuff (component/directive/...) or just reload the page the side panel will be not synced with the opened doc page. Sometimes it may be really hard to find related pages inside the side panel since it contains a lot of links and groups.

### Describe the solution you'd like

Would be nice to see synced side panel to easily find related stuff especially when there are exist a few types, eg inputs, charts, etc

**Comment by vadimk7** [comment]
@MarsiBarsi, @waterplea, what do you guys think about this feature? You can simply mark the issue with appropriate labels and I will tackle this :)

**Comment by waterplea** [comment]
Sure. Sounds like an improvement. Feel free to give it a shot!
