### ISSUE TITLE
[FEATURE] Copy to clipboard for spaces styles by click

### ISSUE THREAD

**Issue by xRoulanDx** [TinkoffCreditSystems/taiga-ui#197]
# 🚀 Feature request

### Is your feature request related to a problem?

I'm always frustrated when I need to copy some class names by hand instead of clicking them and getting the selected class names in the clipboard.

![image](https://user-images.githubusercontent.com/15379294/106523674-828bdf00-64f2-11eb-89db-536d4c0c518f.png)

### Describe the solution you'd like

I want to be able to copy spaces class names to the clipboard by click. Like in the typography section.

**Comment by xRoulanDx** [comment]
Nope xD
![image](https://user-images.githubusercontent.com/15379294/106949968-c7a45100-673e-11eb-9617-f588fec3653c.png)

The layout is so bad. But functionally everything is fine.

**Comment by waterplea** [comment]
Fixed 😆
