### ISSUE TITLE
[FEATURE] Add ability to use ng add

### ISSUE THREAD

**Issue by sh33dafi** [TinkoffCreditSystems/taiga-ui#210]
# 🚀 Feature request

### Is your feature request related to a problem?

Currently starting with Taiga ui you have to do a few manual steps to get started

### Describe the solution you'd like

 It would be nice to leverage angular cli's ng add ability to provide a basic setup.
e.g.
running `ng add @taiga-ui/schematics` will:

-  install minimal libs 
- add theme to angular.json
- include TuiRootModule
- add tui-root wrapper
- ...

### Additional context

If you want I can give it a shot in creating something like that

**Comment by waterplea** [comment]
Sure. We would like that too, just do not have time to learn how to do it properly :) @MarsiBarsi can we have some specs for this?

**Comment by MarsiBarsi** [comment]
Hey 👋 

This is a very cool idea, I like it! I think it would be cool to support the following steps:
1. It asks what libraries user needs. CDK / CDK + Core / CDK + Core + Kit / etc. If there is a possibility to add some additional instructions with packages descriptions, it can be useful to do (we can provide description texts)
2. It adds global styles and asks "Do you need a default Taiga UI theme?"
3. It wraps the app with tui-root and maybe writes some warning that it was done
4. It asks about Dialog and Notification modules and adds them into app.module if the user needs
5. It adds icons

**Comment by waterplea** [comment]
> Hey 👋
> 
> This is a very cool idea, I like it! I think it would be cool to support the following steps:
> 
> 1. It asks what libraries user needs. CDK / CDK + Core / CDK + Core + Kit / etc. If there is a possibility to add some additional instructions with packages descriptions, it can be useful to do (we can provide description texts)
> 2. It adds global styles and asks "Do you need a default Taiga UI theme?"
> 3. It wraps the app with tui-root and maybe writes some warning that it was done
> 4. It asks about Dialog and Notification modules and adds them into app.module if the user needs
> 5. It adds icons

I think with 1 it should always install basic packages. But it can ask for addons.
It should also add `BrowserAnimationsModule`. Maybe it could also ask for ng-dompurify and install it as `TUI_SANITIZER` on positive response.

**Comment by sh33dafi** [comment]
I will give it a shot! ;)

**Comment by patelvimal** [comment]
@sh33dafi Have you done with this? If not I can take this. Please let me know.

**Comment by sh33dafi** [comment]
> @sh33dafi Have you done with this? If not I can take this. Please let me know.

I'm working on it could use some help with integrating it in the build flow

**Comment by nartc** [comment]
@sh33dafi what's your process on this?
