### ISSUE TITLE
Grammar mistakes

### ISSUE THREAD

**Issue by Gromov-Roman** [TinkoffCreditSystems/taiga-ui#211]
https://github.com/TinkoffCreditSystems/taiga-ui/blob/e858b031d860eea16be45daabbe6823304f1f332/projects/cdk/directives/active-zone/active-zone.directive.ts#L80

Check grammar please

**Comment by MarsiBarsi** [comment]
Thank you, we'll fix it ;)

**Comment by waterplea** [comment]
Fixed
