### ISSUE TITLE
[BUG] Scrollbar on Mobile shows twice

### ISSUE THREAD

**Issue by Phmager** [TinkoffCreditSystems/taiga-ui#220]
# 🐞 Bug report

### Description

The Scrollbar Thumb is shown twice in mobile view. It can also be seen with chrom dev tools:

![image](https://user-images.githubusercontent.com/9350951/107501926-51697980-6b98-11eb-9b68-d86a235d0d0a.png)

### Reproduction

https://taiga-ui.dev/tui-scrollbar

### Expected behavior

Only show normal mobile scroll thumb and not custom thumb

### Versions

-   OS: iOS / Windows
-   Browser Safari / Chrome Device Emulator

**Comment by waterplea** [comment]
Global scrollbar should not be visible on mobile devices. I don't see this bug on my Samsung phone. Will try an iPhone when I can soon.
