### ISSUE TITLE
[BUG] Dialog closes by click outside when dismissible is true

### ISSUE THREAD

**Issue by kapitan7830** [TinkoffCreditSystems/taiga-ui#230]
# 🐞 Bug report

### Description

If you set the option dismissible to false and click on the border (tui-dialog has css style: border: 40px solid transparent;) dialog will close.

### Reproduction

![Screenshot_2021-02-19_00-25-37](https://user-images.githubusercontent.com/14724487/108396781-d06e4a00-7249-11eb-9a0b-74d1aceea618.png)

### Expected behavior

Dialog won't close.

### Versions

-   OS: linux
-   Browser: chrome
-   Angular 11
-   Package @taiga-ui/core 2.5.0

**Comment by waterplea** [comment]
Thank for spotting and reporting it! Looks like that's a by-product of a fix for another issue. We'll get that resolved in the next release, hopefully in a couple of days.
