### ISSUE TITLE
[FEATURE] Speed up animationso of allow to configure animation speed

### ISSUE THREAD

**Issue by JohanHeyvaert** [TinkoffCreditSystems/taiga-ui#235]
# 🚀 Feature request

### Is your feature request related to a problem?
I feel all animations are a bit too slow. E.g. when clicking on a tuiDropdown the contents is opened quite slowly. It feels sluggish instead of snappy.

### Describe the solution you'd like
The animations could be a little faster by default. If possible it would be very convenient if this could be configured somehow (via directive itself and/or a global config).

### Describe alternatives you've considered
I have searched a bit but I don't see how I could change this myself without changing the source code (I think the releated code is here: https://github.com/TinkoffCreditSystems/taiga-ui/search?q=TUI_ANIMATION_DURATION ).

### Additional context
If you know of a quick workaround I would be happy to use it

Thank!

**Comment by waterplea** [comment]
In the next version you will be able to control all animations/transitions with `TUI_ANIMATIONS_DURATION` DI token.

**Comment by JohanHeyvaert** [comment]
Thanks a lot!
