### ISSUE TITLE
[FEATURE] New icons request

### ISSUE THREAD

**Issue by makkaronis4e** [TinkoffCreditSystems/taiga-ui#236]
# 🚀 Feature request

Add new icons: cart, save, compare

something like these:
![image](https://user-images.githubusercontent.com/33792090/108885513-949fff80-7610-11eb-96be-06b4925e7434.png)
![image](https://user-images.githubusercontent.com/33792090/108885578-abdeed00-7610-11eb-9463-727a797432e4.png)
![image](https://user-images.githubusercontent.com/33792090/108885653-bdc09000-7610-11eb-925e-5e2b2a1f356c.png)

**Comment by waterplea** [comment]
We use Feather icons in Taiga (mostly). I asked our designer to unload full pack, but I'm not sure when he would have time to process them.

**Comment by waterplea** [comment]
I think we can close this issue for now, we will be adding new icons every now and then, but if you want custom icons it's already possible.
