### ISSUE TITLE
[DOCS] Document TUI_SANITIZER usage

### ISSUE THREAD

**Issue by MarsiBarsi** [TinkoffCreditSystems/taiga-ui#250]
```
    {
      provide: TUI_SANITIZER,
      useClass: NgDompurifySanitizer
    }
```

**Comment by waterplea** [comment]
I don't want to make the getting started page too crowded. If icons are used as assets there's no need for custom sanitizer. Perhaps it's better to add assertion of svg ends up falling back to source inlinement and TUI_SANITIZER was not provided.
