### ISSUE TITLE
[BUG] Sidebar/ activezone wrongly emits tuiActiveZoneChange

### ISSUE THREAD

**Issue by makkaronis4e** [TinkoffCreditSystems/taiga-ui#251]
# 🐞 Bug report

### Description

I have buttons in sidebar created with ngFor which represent some array/object. If button onclick removes related element from array or property from object, i'm getting ExpressionChangedAfterItHasBeenCheckedError + sidebar collapsing.

For me it appears only for buttons and component-tags with nested elements which perform element deletion on click, but with div/span works fine.

Seems like activezone directive treats clicks on these elements like clicks outside activezone.

### Reproduction

https://stackblitz.com/edit/angular-rppmq4?file=src%2Fapp%2Fexpamle.component.ts

### Versions
-   Angular 11
-   Package @taiga-ui@2.6.1

Bug appears only in Chrome (tested also in firefox and safari, works fine)

**Comment by waterplea** [comment]
It happens because element gets destroyed and focus goes nowhere so zone thinks you left it. For some reason it doesn't happen when you focus button with keyboard first, so the focus is shown with a border. I'll need to debug that stuff :)
