### ISSUE TITLE
[BUG] Docs examples: app.log service usage

### ISSUE THREAD

**Issue by EnoRage** [TinkoffCreditSystems/taiga-ui#252]
# 🐞 Bug report (documentation)

### Description

https://taiga-ui.dev/tui-link

There is an app.log import there, looks like it is breaking some builds on stackBlitz

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

<img width="745" alt="Screenshot 2021-02-27 at 15 50 40" src="https://user-images.githubusercontent.com/22479658/109387628-8d7c3880-7913-11eb-8a49-c3769b037db6.png">

<img width="893" alt="Screenshot 2021-02-27 at 15 50 52" src="https://user-images.githubusercontent.com/22479658/109387634-9705a080-7913-11eb-814c-61f27c6595c3.png">

### Reproduction

1. Open docs: https://taiga-ui.dev/tui-link
2. Open stackBlitz: https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

### Expected behavior

No logs import

### Versions

Docs v2.6.1

### Additional context

Great kit! It will be awesome to have some other examples like this:
https://www.creative-tim.com/product/material-dashboard-angular2
https://demos.creative-tim.com/material-dashboard-angular2/#/dashboard

**Comment by waterplea** [comment]
@MarsiBarsi should we, probably, get rid of this service at all? Looks unnecessary.

**Comment by MarsiBarsi** [comment]
I agree...
Such entities blur focus from our components, their usage and API

**Comment by MarsiBarsi** [comment]
Thank you @EnoRage for your issue and idea. The dashboard is a great idea to show the power of Taiga UI. Once, we'll do it :)
