### ISSUE TITLE
Make the `autoClose` timeout of `TuiNotificationsService` configurable

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#253]
# 🚀 Feature request

It would be great it the `autoClose` delay when showing a notification is configurable.  At the moment it is hard coded to 3000ms (https://github.com/TinkoffCreditSystems/taiga-ui/blob/854b544e87a8916703ecdb8624757b602b3e9a40/projects/core/modules/notifications/notification-alert/notification-alert.component.ts#L10)

**Comment by waterplea** [comment]
Hi @jonsamwell 

This can be easily implemented on app side with takeUntil + timer:
https://stackblitz.com/edit/taiga-autoclose

Feel free to comment/reopen if you have further questions!

**Comment by waterplea** [comment]
Now when notifications will not be auto closed when you hover them it makes sense to make time configurable. Reopening it. I wonder if making autoClose type boolean | number would be a good API extension. What do you think, @MarsiBarsi?

**Comment by MarsiBarsi** [comment]
> Now when notifications will not be auto closed when you hover them it makes sense to make time configurable. Reopening it. I wonder if making autoClose type boolean | number would be a good API extension. What do you think, @MarsiBarsi?

Well, I would like to make it `closeAfterMs: number` with `closeAfterMs: Infinity` instead of `false`. But boolean | number option is okay to prevent breaking change for now
