### ISSUE TITLE
TuiColorHandler in charts does not allow for hex/rgb colour strings

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#271]
At the moment a colour handler only seems to work if a TuiColor is returned not a valid colour string such as hex or rgb(a).  Is this on purpose? If so is there any way colour string can be supported i.e. '#4455FA' / 'rgba(125, 55, 255, 0.5)' etc.

**Comment by waterplea** [comment]
@jonsamwell please take a look at the new easy API for setting colors in charts with CSS vars:
https://taiga-ui.dev/components/pie-chart#labels
See "LESS" tab. `TuiColorHandler` is now _deprecated_.
