### ISSUE TITLE
Table TH Sorter to allow server side sorting

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#275]
# 🚀 Feature request

### Is your feature request related to a problem?

At the moment the `tuiTH` only allows for client side sorting via the `[sorter]` function.  With large, paged dataset this is not viable and server sorting is preferred.

### Describe the solution you'd like

It would be great it we could have the current sort ui on a header cell but an event triggered when a `th` is clicked that provides the column name and sort direction.  This way a request could be initiated to the server with the new sort property and order

This would obviously have to disable the client side sorter function

**Comment by ramax495** [comment]
The same thing is with filtering and paging.

**Comment by jonsamwell** [comment]
@ramax495 I was able to use the events on `TablePagination` component, they are just not documented

```
    <tui-table-pagination class="mt-2" *ngIf="countriesCollection | async as data" [items]="pageSizes"
      [total]="data.totalItems" [page]="data.page - 1" [size]="data.pageSize" (sizeChange)="onPageSizeChanged($event)"
      (pageChange)="onPageChanged($event)"></tui-table-pagination>
```

```
  public onPageSizeChanged(size: number): void {
    this.updatePageData((data) => {
      data.size = size;
      data.page = 1;

      return data;
    });
  }

  public onPageChanged(page: number): void {
    this.updatePageData((data) => {
      if (data.page !== (page + 1)) {
        data.page = page + 1;

        return data;
      }

      return undefined;
    });
  }

  protected updatePageData(cb: (data: PageRequest) => PageRequest | undefined): void {
    this.subscribeOnce(
      this.bloc.pageRequest,
      {
        onData: (data) => {
          const result = cb(data);
          if (result) {
            this.bloc.pageRequest.next(result);
          }
        }
      }
    );
  }

```

**Comment by waterplea** [comment]
Please take a look at the most recent example we've added:
https://taiga-ui.dev/components/table#server
I think it covers your usecases.
