### ISSUE TITLE
[BUG]  ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by 500x500** [TinkoffCreditSystems/taiga-ui#288]
# 🐞 Bug report

### Description

There is an error in console, when I click in IputPasswords button show/hide password
```Expression has changed after it was checked. Previous value: 'Скрыть пароль'. Current value: 'Показать пароль'.```
### Reproduction
<tui-root>

  <tui-island size="l" textAlign="center">
    <h2 class="title">Вход в систему</h2>
    <tui-input class="b-form"> Имя пользователя </tui-input>

    <tui-input-password class="tui-space_top-2">
      Введите пароль
    </tui-input-password>

    <button
          tuiButton
          type="button"
          class="tui-island__footer-button"
          appearance="flat"
          (click)="onSubmit()"
          size="l">
          Войти
        </button>
  </tui-island>
</tui-root>

https://stackblitz.com/edit/taiga-starter-yehbav?embed=1&file=src/app/app.component.html

### Expected behavior

Without Error of course :)
### Versions
- OS MacOs Latest
-   Browser [chrome latest]
-   Angular [e.g. 11]
-   Package [e.g. @taiga-ui/cdk latest]

### Additional context
Also I plan Taiga Ui as Main ui-kit in new healthcare project in Russia. I think it can be a united standard of ui in our app's (other 2 projects on Material UI, but it has some problems with customization)

**Comment by MarsiBarsi** [comment]
Thanks for your issue!
