### ISSUE TITLE
[FEATURE] InputCount - allow to provide number with decimal point

### ISSUE THREAD

**Issue by Olgagr** [TinkoffCreditSystems/taiga-ui#301]
# 🚀 Feature request

Right now this is not possible to have a step like 0.5. It would be nice to allow that as well.

### Describe the solution you'd like

Allow to define the step from range 0..1

**Comment by waterplea** [comment]
InputCount is designed for whole numbers. For decimal it's better to use InputNumber or InputSlider. Is there a reason you need a stepped (with arrow buttons) input for decimals?

**Comment by Olgagr** [comment]
I have a control where user needs to provide number of years of experience. I need a step there like in the InputCount and my step is 0.5. I can use number field there but it doesn't provide steps.

**Comment by waterplea** [comment]
This is a fundamental change and I think it's not going to happen per design system behind Taiga. If you need mouse control you would have to use InputSlider. Check out this little example:
https://stackblitz.com/edit/taiga-years-experience

**Comment by Olgagr** [comment]
@waterplea Thanks for response! I think this is something that might solve my problem 😄
