### ISSUE TITLE
[BUG] input time with dropdown only works on arrow keys

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#307]
# 🐞 Bug report

### Description

input time with dropdown only works on arrow keys, not on input focus or mouse click

### Reproduction

Visit:
https://taiga-ui.dev/components/input-time#dropdown
or
https://stackblitz.com/edit/angular-spfd4l?file=src/app/app.component.ts

Try to open the dropdown with mouse only.

### Expected behavior

Dropdown should open icon click or input focus (maybe configurable)

### Versions

-   OS: Windows
-   Browser: Chrome
-   Angular as per demo

**Comment by waterplea** [comment]
It was discussed with internal team a few days before you raised it and it was agreed upon opening it on click of the whole input, like `InputDate` and similar controls behave :) Of course only if there are items to pick from. I'll add a fix soon.
