### ISSUE TITLE
[BUG] Dialog example is broken on stackblitz.com

### ISSUE THREAD

**Issue by Olgagr** [TinkoffCreditSystems/taiga-ui#308]
# 🐞 Bug report

### Description

Can you provide some working and complete example on stackblitz.com how to use Dialogs, please?

### Reproduction

In docs: https://taiga-ui.dev/dialogs, when going to stackblitz.com the example is broken.

**Comment by waterplea** [comment]
Let's track dialog examples in one issue:
https://github.com/TinkoffCreditSystems/taiga-ui/issues/383
