### ISSUE TITLE
Stepper add tail

### ISSUE THREAD

**Issue by AnteaterKit** [TinkoffCreditSystems/taiga-ui#312]
Hi!
The designer create a stepper with a tail. I try to add tail with a directive and QueryList and it's work. 
But the TuiStepComponent have a private elementRef. Could i add pr to make it public? 

<img width="949" alt="Screenshot 2021-03-27 at 10 45 37" src="https://user-images.githubusercontent.com/5115677/112714092-add6ed00-8ee9-11eb-8fc5-e08da81fc652.png">

**Comment by waterplea** [comment]
Can you show your code? Perhaps you can do read: ElementRef?

**Comment by AnteaterKit** [comment]
It's not for prod, it's only guess to solve task.
<img width="981" alt="Screenshot 2021-03-27 at 11 40 12" src="https://user-images.githubusercontent.com/5115677/112715442-4329af80-8ef1-11eb-8c4e-2ea83cfdb9af.png">
<img width="892" alt="Screenshot 2021-03-27 at 11 40 21" src="https://user-images.githubusercontent.com/5115677/112715445-46bd3680-8ef1-11eb-97fc-3393e7100767.png">

**Comment by waterplea** [comment]
It think it's best to solve this with CSS and pseudo elements:
https://stackblitz.com/edit/angular-ghvuqb

**Comment by waterplea** [comment]
Looks like this resolves the issue, but just in case, you can also get access to `ElementRef` by directly reading it:
```ts
@ContentChildren(
  TuiStepComponent,
  {
    read: ElementRef,
  },
)
readonly items!: QueryList<ElementRef>;
```
