### ISSUE TITLE
[BUG] changing multiselect medium height

### ISSUE THREAD

**Issue by KarimovDev** [TinkoffCreditSystems/taiga-ui#327]
# 🐞 Bug report

### Description

If you change variable --tui-height-m to 40px, multiselect will be 44px anyway.

### Reproduction

Works for multiselect with [tuiTextfieldLabelOutside]="true" [expandable]="false".
https://stackblitz.com/edit/angular-ms3ukr

### Expected behavior

Changing height through variables should change multiselect height properly.

### Versions

-   OS: [MacOS]
-   Browser [Chrome 89.0.4389.114 ARM64, Safari 14.0.3 (16610.4.3.1.7)]
-   Angular [11.2.3]
-   Package [@taiga-ui/kit@2.7.0]

### Additional context

It happens due to tui-scrollbar height inside tui-input-tag. I can fix it with adding CSS class for tui-scrollbar depending on controller size. If it is OK, I will push an PR.

**Comment by nsbarsukov** [comment]
Hi, @KarimovDev 

Unfortunately, there are reasons why we cannot make `m`-size input less than `44px`. You can only make it **more** than `44px`.

But we added support size `s` for the `multi-select` (**it will be released soon** :tada:).
`S`-size input can  be`32px` or **more**. 

Use `tuiTextfieldSize` = `s` and configure `--tui-height-s` to desirable height (>= 32px).

**Comment by KarimovDev** [comment]
Thank you! Will wait the release

**Comment by KarimovDev** [comment]
@nsbarsukov In my case I've fixed this with
`
.tags {
  max-height: var(--tui-height-m);
}
`
