### ISSUE TITLE
Calendar startDayOfTheWeek

### ISSUE THREAD

**Issue by elawady55** [TinkoffCreditSystems/taiga-ui#341]
Hi,
I would like to know how I can change the start day of the week from Monday to Sunday and I couldn't find any resource how I can do this

**Comment by waterplea** [comment]
Hi @elawady55 

Localization of date formats is not yet implemented. We plan to work towards better localization this quarter:
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/ROADMAP.md
