### ISSUE TITLE
[BUG] NullInjectorError: No provider for TuiScrollService

### ISSUE THREAD

**Issue by marcoripa96** [TinkoffCreditSystems/taiga-ui#354]
# 🐞 Bug report

### Description

Whenever I inject the TuiScrollService into a component it throws a NullInjectorError

### Reproduction

https://stackblitz.com/edit/taiga-starter-zuncen?file=src%2Fapp%2Fapp.component.ts

### Expected behavior

It should inject the service without throwing any error.

### Versions

-   OS: Windows 10
-   Browser: Chrome v90.0.4430.85
-   Angular 11
-   Package @taiga-ui/cdk@2.7.0

**Comment by waterplea** [comment]
Thank you for raising it. @nikitadubinsk I think we can add providedIn root to this service, there's no reason for more than one instance of it.
