### ISSUE TITLE
[BUG] Unable to build latest release (2.8.2)

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#373]
# 🐞 Bug report

### Description

I get the following errors when building release 2.8.2:

ERROR: node_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts:7:24 - error TS2416: Property 'component' in type 'TuiDialogService' is not assignable to the same property in base type 'AbstractTuiDialogService<TuiDialogOptions<any>>'.
  Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusContent<TuiDialog<TuiDialogOptions<any>, 
any>>'.
    Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusComponent<object, TuiDialog<TuiDialogOptions<any>, any>>'.
      Types have separate declarations of a private property 'injector'.

7     protected readonly component: PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>;
                         ~~~~~~~~~

An unhandled exception occurred: node_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts:7:24 - error TS2416: Property 'component' in type 'TuiDialogService' is not assignable to the same property in base type 'AbstractTuiDialogService<TuiDialogOptions<any>>'.
  Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusContent<TuiDialog<TuiDialogOptions<any>, 
any>>'.
    Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusComponent<object, TuiDialog<TuiDialogOptions<any>, any>>'.
      Types have separate declarations of a private property 'injector'.

7     protected readonly component: PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>;

### Expected behavior

The library builds without error

### Versions

-   OS: Windows
-   Browser [e.g. chrome, safari]
-   Angular ~11.2.12
-   Node: v14.15.4
-   NPM: 6.14.10

### Additional context
V2.8.0 builds without error.

Build error log

```
[error] Error: [96mnode_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts[0m:[93m7[0m:[93m24[0m - [91merror[0m[90m TS2416: [0mProperty 'component' in type 'TuiDialogService' is not assignable to the same property in base type 'AbstractTuiDialogService<TuiDialogOptions<any>>'.
  Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusContent<TuiDialog<TuiDialogOptions<any>, any>>'.
    Type 'PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>' is not assignable to type 'PolymorpheusComponent<object, TuiDialog<TuiDialogOptions<any>, any>>'.
      Types have separate declarations of a private property 'injector'.

[7m7[0m     protected readonly component: PolymorpheusComponent<TuiDialogComponent<unknown, unknown>, object>;
[7m [0m [91m                       ~~~~~~~~~[0m

    at Object.compileSourceFiles (C:\easilog\web-app-rewrite\easilog\node_modules\ng-packagr\lib\ngc\compile-source-files.js:61:15)
    at async C:\easilog\web-app-rewrite\easilog\node_modules\ng-packagr\lib\ng-package\entry-point\compile-ngc.transform.js:35:13
```

**Comment by waterplea** [comment]
We bumped Polymorpheus version. Try removing node modules and package-lock and reinstall everything completely. Also ng-polymorpheus should not present in your package.json as it goes with cdk as dependency. Your error looks like a version mismatch as if you have 2 different versions in your project.

**Comment by jonsamwell** [comment]
@waterplea thanks for the info.  I have ng-polymorpheus as a package dependencies removing that and following your steps enable me to build.

However, I am now getting errors for polymorpheus content for type conversions unfortunately.  I think the problem is that a `PolymorpheusTemplate` has a generic parameter with a default value of object.  Whereas something like `tui-ring-chart` expects a content parameter of `PolymorpheusContent<TuiRingChartContext>` so the angular compiler doesn't seem to be able to infer the type here.  Am I missing something as we can't type these `ng-template polymorpheus` templates?

![image](https://user-images.githubusercontent.com/3694497/117250604-cf32dd80-ae86-11eb-9058-98e4f1bb4c18.png)

**Comment by waterplea** [comment]
@jonsamwell we now can type the templates, this is exactly the change we've made. See this example:
https://github.com/TinkoffCreditSystems/ng-polymorpheus#adding-type-to-template-context
However in your case there's no need to use polymorpheus at all, you can just pass a regular ng-template.

@MarsiBarsi @WynieCronje looks like this typing addition broke basic use. Do you have a suggestion how to fix that? Maybe add `any` as default generic? `PolymorpheusTemplate<T extends object = any>`

**Comment by MarsiBarsi** [comment]
Hey all
@waterplea if we still want to have an object here, we can use `Record<any, any>` type as default, right?

**Comment by jonsamwell** [comment]
@waterplea thanks for this all working as expected after typing the templates.  Shall I close this issue or do you want to keep it open to track the typing change?

@waterplea ```Record<any, any> | string | number | boolean``` might be best to account for primitive types as well?

Thanks for an awesome library that is a pleasure to work with!!!!

**Comment by waterplea** [comment]
I'm glad you liked the library 🙂 I'll keep it open until we decide what to do with default generic. In theory, you shouldn't use primitives as context. It would work with functions or components, but not templates — you will not be able to get anything from context since you are reaching by key:

```html
<ng-template let-value="key">
```

**Comment by WynieCronje** [comment]
@waterplea  The example in the `ng-polymorpheus README.md` uses a primitive type?
![image](https://user-images.githubusercontent.com/4537265/117402899-8cfdb080-af07-11eb-9f2a-3a52cad1d509.png)

Or am I confused :D

Maybe some developers do this. And a `any` is a better default?

What do you think @MarsiBarsi ?

**Comment by waterplea** [comment]
> @waterplea  The example in the `ng-polymorpheus README.md` uses a primitive type?
> ![image](https://user-images.githubusercontent.com/4537265/117402899-8cfdb080-af07-11eb-9f2a-3a52cad1d509.png)
> 
> Or am I confused :D
> 
> Maybe some developers do this. And `any` is a better default?
> 
> What do you think @MarsiBarsi ?

It is using an object with `$implicit` key — that is a default key that can be used without explicitly referencing (`let-value` instead of `let-value="value"`).

**Comment by WynieCronje** [comment]
Nice, if it is impossible to use template context without an object.

I will vote `Record<any, any>` as the default generic

**Comment by waterplea** [comment]
Got it fixed finally. Wasn't as easy as defining default generic :) I will upgrade Taiga to the latest polymorpheus in the next version.

**Comment by the-ult** [comment]
Not sure if it is related:

When using the [ringchart](https://taiga-ui.dev/components/ring-chart)

This is the current (example) code.
```html
<tui-ring-chart [value]="value" [content]="content"></tui-ring-chart>
 
<ng-template #content="polymorpheus" polymorpheus let-index>
    <tui-money [singleColor]="true" [value]="getValue(index)"></tui-money>
    <div>{{getLabel(index)}}</div>
</ng-template>
```
Is this correct or should it be changed to:
```html
<tui-ring-chart [value]="value" [content]="content"></tui-ring-chart>
 
<ng-template #content="polymorpheus" [polymorpheus]="context" let-index>
    <tui-money [singleColor]="true" [value]="getValue(index)"></tui-money>
    <div>{{getLabel(index)}}</div>
</ng-template>
```

When I remove `ng-polymorpheus` from the `package.json` I get the Error, that `polymorpheus` cannot be found.
Should we still import `PolymorpheusModule`? And from which library?
(The stackblitz example still uses `ng-polymorpheus` https://stackblitz.com/run?file=package.json )

```
error NG8003: No directive found with exportAs 'polymorpheus'.

 <ng-template #content="polymorpheus" [polymorpheus]="context" let-index>

```

**Comment by waterplea** [comment]
In this case you probably can just drop polymorpheus and use regular template. But you shouldn't have polymorpheus in your package.json — try removing node modules and package-lock.json and doing clear npm i

**Comment by the-ult** [comment]
Thanks.
So the example code on [taiga-ui](https://taiga-ui.dev/components/ring-chart) is not correct/up to date?
(and the stackblitz isn't either)

**Comment by waterplea** [comment]
It's not necessarily incorrect, it's superfluous. If hint template had a button that should be triggering change detection on the parent component (say it changed some value on click) — then directive would be necessary. This is exactly why it was created — to sync change detection. But here it's not needed and we should probably remove it from the demo (and in most cases where it's used on the demo), thank you for spotting it!

**Comment by the-ult** [comment]
Thanks. removing it, simplifies it 👍
