### ISSUE TITLE
[BUG] Preprocess-icons script variable name undefined

### ISSUE THREAD

**Issue by marcoripa96** [TinkoffCreditSystems/taiga-ui#390]
# 🐞 Bug report

### Description

I was trying to add new icons as assets and, as suggested by the documentation, run the `preprocess-icons.js` script inside the folder where the icons are placed. The script doesn't define the name of the icon and it crashes.

Simply replacing the following line:
```javascript
const wrapped = wrapIcon(src, file.replace('.svg', ''));
```
with the following lines:
```javascript
const name = file.replace('.svg', '');
const wrapped = wrapIcon(src, name);
```
should resolve the issue.

### Reproduction

Place the script inside the folder where the new icons are and the run `node preprocess-icons.js`. 

### Expected behavior

Execute the script without any error and generate suitable icons to use with the `TuiSvgComponent`.

### Versions

-   OS: Windows 10
-   Browser: Chrome v90.0.4430.93
-   Angular 11

**Comment by waterplea** [comment]
@marcoripa96 hello and thank you for trying this feature. Could you share a few icons that cause it to crash? I don't see how your proposed change could fix it or how an svg icon could not have the name so I would like to fiddle with those files locally to debug what's going on. You can just replace content with some dummy svg if those icons are proprietary.

**Comment by waterplea** [comment]
@marcoripa96 kind reminder ☝🙂

**Comment by waterplea** [comment]
Oh, wow, I've been looking at a copy of that script in our private repo. Looks like some merge conflict left undefined constant there. Thank you, I'll get it fixed in the next version!

**Comment by marcoripa96** [comment]
No problem! Thank you for your work!

**Comment by waterplea** [comment]
It is fixed now, not sure since what version though. Thanks for reporting!
