### ISSUE TITLE
[BUG] Duplicate icons set in demo

### ISSUE THREAD

**Issue by Goodzonchik** [TinkoffCreditSystems/taiga-ui#392]
# 🐞 Bug report

Icon names are duplicated when opening the page https://taiga-ui.dev/icon-set and click "show names" button.

This is because duplicate names in constants-flie and in demo-flie.

In file "taiga-ui/projects/icons/constants/icons.ts " tuiKitIcons include tuiCoreIcons. line 46
`ts
    export const tuiKitIcons = {
    ...tuiCoreIcons,
    ...
`

In file "taiga-ui/projects/demo/src/modules/customization/icon-set/icon-set.component.ts" line 21.
`ts
readonly names = [...Object.keys(tuiCoreIcons), ...Object.keys(tuiKitIcons)];
`

**Comment by waterplea** [comment]
@Goodzonchik Nice catch, thank you! Would you be interested in creating a PR since you already spotted where and how it has to be fixed? 🙂

**Comment by Goodzonchik** [comment]
Ok, I create PR for this bug)
https://github.com/TinkoffCreditSystems/taiga-ui/pull/401

**Comment by waterplea** [comment]
Resolved with your PR, thank you!
