### ISSUE TITLE
[FEATURE] prefix TUI classes and generic elements

### ISSUE THREAD

**Issue by sdurnov** [TinkoffCreditSystems/taiga-ui#405]
# 🚀 Feature request

### Is your feature request related to a problem?

Updating some old project to Taiga. Both have elements like section (used for your dialog content), classes like header, and so on, which conflicts with each other.

### Describe the solution you'd like

would be nice to have your generic elements to have classes like tui-<class name> and your existing classes to get a tui- prefix.

### Describe alternatives you've considered

I have to modify old app selectors to resolve the conflicts. Sometimes :not helps, but won't help if selector is multi-level.

**Comment by waterplea** [comment]
I believe that it's global classes that should be prefixed, not the component classes. This is why we have encapsulation in Angular. Otherwise we would have to have every class prefixed which is a lot of noise.

**Comment by waterplea** [comment]
I will keep this open and mark it with appropriate labels. Our global classes are prefixed with `tui-`, maybe we can use `t-` for all internal classes. This wouldn't hurt to do and wouldn't introduce any breaking changes to people, unless they hacked into our internal classes to tweak something. The priority for this would be rather low, so it would probably be better for you to prefix your global styles. This is a good practice anyway.
