### ISSUE TITLE
[BUG] InputDateRange + maxLength of 1 month

### ISSUE THREAD

**Issue by waterplea** [TinkoffCreditSystems/taiga-ui#418]
# 🐞 Bug report

### Description

If you set `maxLength` for `InputDateRange` to be `{ month: 1 }` months in date picker start to behave a little crazy:
1. picking the first day of a month in left calendar switches all calendars 1 month in the past so selected day is now in the right calendar
2. picking last day of the right month switches both calendars to show the same month

### Reproduction

https://stackblitz.com/edit/taiga-date-picker-bug

**Comment by artemv01** [comment]
Hi there, i'd like to check out this one

**Comment by artemv01** [comment]
> picking the first day of a month in left calendar switches all calendars 1 month in the past so selected day is now in the right calendar

@waterplea that looks like the expected behaviour? From the code, when we select `maxLength` we want to show that exact number of days/months both from right and left side of the selected day in the calendar. In case of `maxLength: {month: 1}` If we select the first day of the month in the left calendar, we want also to see the dates of the previous months, that's why we switch the left side to the previous month, and the right side will show the month that previously was on the left side along with the selected day . Pls let me know if i'm wrong here.

**Comment by waterplea** [comment]
> > picking the first day of a month in left calendar switches all calendars 1 month in the past so selected day is now in the right calendar
> 
> @waterplea that looks like the expected behaviour? From the code, when we select `maxLength` we want to show that exact number of days/months both from right and left side of the selected day in the calendar. In case of `maxLength: {month: 1}` If we select the first day of the month in the left calendar, we want also to see the dates of the previous month, that's why we switch the left side to the previous month, and the right side will show the month that previously was on the left side along with the selected day . Pls let me know if i'm wrong here.

That sounds reasonable but I think if user clicks on the left calendar they most likely want to pick the start of the interval so it's important that the right side shows more days. I would expect it not to switch.

**Comment by artemv01** [comment]
>That sounds reasonable but I think if user clicks on the left calendar they most likely want to pick the start of the interval so it's important that the right side shows more days. I would expect it not to switch.

let me clarify here. For example if user picks 1st day on the left side and the month happen to have any amount of days we still limit selection to the left side only coz of the limit `maxLength: {month: 1}`. This is correct?

On the other side, if user picks the _last day_ either on left / right side i.e. 31 May _on the right side_, then in this case we switch 31 May to the left side and show June on the other side. That's ok?

**Comment by waterplea** [comment]
I'm not sure. I think that the less unexpected jumps the better. I suppose it's best I ask our designer how to handle this case. I think it feels best when I click some day that it remains in place, just changes to selected.

**Comment by waterplea** [comment]
@artemv01 designer responded that there should be no automatic jumps at all.

**Comment by artemv01** [comment]
ok @waterplea then we can just block the dates before 29th in the right screen and allow next days within a month but not switch screens.

**Comment by artemv01** [comment]
Or better : just like now , allow 30 days from a selected day and after it. But in case those days cross the date when we need to do the jump, we're gonna allow just enough days to not do the jump @waterplea

**Comment by waterplea** [comment]
I don't get it ) we just need not to change months automatically, only when user changes when manually 🙂

**Comment by artemv01** [comment]
yeah that's what I meant, ok
