### ISSUE TITLE
[BUG] `InputPhone` removing value leave country code

### ISSUE THREAD

**Issue by waterplea** [TinkoffCreditSystems/taiga-ui#419]
# 🐞 Bug report

### Description

When you hit backspace and remove whole number of `InputPhone`, then click away — country code remains in the input, although it is treated as empty value (label flies down). It disappears on the next focus. Can be reproduced on demo portal:
https://taiga-ui.dev/components/input-phone

**Comment by BharathRavi27** [comment]
WOuld like to know more about this. What would be the ideal case we are looking at here? 

1. When there's no input value, we hide the country code
2. Always have country code displayed(Fix the disappearing issue)

**Comment by waterplea** [comment]
Right. That's a bug, in our internal 1.x version it worked like that:

1. If there is only the country code in the input, the control value is empty line
2. If you leave the field with just the country code - it disappears from control
3. If you enter the field again it re-appears

So 2 and 3 are off now, as if they are lagging one step behind :)

**Comment by herodot-filipwiniarski** [comment]
There seems to be one thing lagging behind - while focusing out, pipe still shows `focused` as true - always one step behind.

**Comment by filipwiniarski** [comment]
There seems to be one thing lagging behind - while focusing out, pipe still shows `focused` as true - always one step behind. Not easy to dig into those inputs for the first time, slowly getting there 😄

**Comment by filipwiniarski** [comment]
@waterplea To me it looks like `PrimitiveTextfield` would need to update model somewhere during `onFocused` event so that `angular2-text-mask` had a proper state in its pipe transformations. Other option would be to change pipe behaviour somehow 🤔

**Comment by waterplea** [comment]
Turned out to be an issue with `ActiveZone` emitting `false` on click while focus was still in the component. Refactored it to wait for next `focusout` event.
