### ISSUE TITLE
[BUG] - addon-table - defaultSort case issue

### ISSUE THREAD

**Issue by WynieCronje** [TinkoffCreditSystems/taiga-ui#424]
# 🐞 Bug report

### Description

`import { defaultSort } from '@taiga-ui/addon-table';`

default sort from addon-table does not sort alphabetically

### Reproduction

https://stackblitz.com/edit/taigaui-defaultsort?file=src/app/app.component.html

### Expected behavior

Should sort alphabetically `A, a, B, b, C, c` and not `A, B, C, a, b, c`

### Additional context

Maybe use `String.prototype.localeCompare` when the type is string

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by waterplea** [comment]
Nice catch! Care for a PR? :)

**Comment by WynieCronje** [comment]
Will create one in coming days. 1st wanted to log issue to link a PR :D
