### ISSUE TITLE
[BUG] TuiTabs with routerLink gets wrong underline on remove

### ISSUE THREAD

**Issue by ikurilov** [TinkoffCreditSystems/taiga-ui#431]
# 🐞 Bug report

### Description

Underline disappears when close previous tab several times.

### Reproduction

Stackblitz: https://stackblitz.com/edit/taiga-starter-pyoyqf

1. Go to https://taiga-starter-pyoyqf.stackblitz.io/?param=4
2. Close tab **Item#0**
3. Underline is ok
4. Close tab **Item#1**
5. Underline is disappeared

<img width="785" alt="Снимок экрана 2021-05-21 в 18 35 54" src="https://user-images.githubusercontent.com/19654800/119164379-0a2b3880-ba65-11eb-8393-7d31272934d3.png">
<img width="786" alt="Снимок экрана 2021-05-21 в 18 36 04" src="https://user-images.githubusercontent.com/19654800/119164397-0eefec80-ba65-11eb-85b7-d4056821b4cf.png">

### Expected behavior

Underline corresponds to activated route

### Versions

-   OS: [macOS 10.15.7]
-   Browser [chrome 90.0.4430.212]
-   Angular [12.0.0]
-   Package [@taiga-ui/kit@2.9.1]

### Additional context

Almost the same happens with **tui-tabs-with-more**

**Comment by waterplea** [comment]
Hi! Thank you for reporting this. Looks like whenever tabs children change we need to re-query routerLinkActives and refresh index.
