### ISSUE TITLE
[FEATURE] Disabled tui-root Scroll Bar

### ISSUE THREAD

**Issue by benfl3713** [TinkoffCreditSystems/taiga-ui#478]
# 🚀 Feature request

### Is your feature request related to a problem?

I already use custom scrolling in my webapp, and when adding the `<tui-root>` element to my app it causes there to be 2 different scroll bars. 
I'm not fully sure if this isn't already a feature, I could not find any documentation on it.

### Describe the solution you'd like

I'd ideally like a property on the tui-root component that would allow a user to disable the custom scrolling
E,g
```html
<tui-root [disabledScrolling]="true"></tui-root>
```

### Describe alternatives you've considered

I'm not really sure there could be any other ways to control this other then possible write some css to override the normal behavior to make the scroll bar have a width of 0

**Comment by waterplea** [comment]
Hi @benfl3713. Thank you for bringing this up. You can hide `tui-root` scrollbar with this global style:
```
tui-root > tui-scroll-controls {
  display: none;
}
```
BTW, we use custom global scrollbar so we can hide it when modal dialogs are open. We need to think how best to handle this if we want to make them configurable.

**Comment by benfl3713** [comment]
Thanks @waterplea that worked great 👍🏻

**Comment by khalilou88** [comment]
@waterplea Hi Alex, I want to disable the scrollbar when I open the Sidebar in my case.
I didn't find how you did that in the case of modal for inspiration.

Thanks

**Comment by waterplea** [comment]
@khalilou88 it's kind of hardcoded in tui-root. I suppose it's a good idea to get an API in place for that.

**Comment by khalilou88** [comment]
@waterplea thanks for your reply.
An api ? like a token (TUI_ROOT_SCROLL_REF) that contains the element "tui-root > tui-scroll-controls"
And hide/show the scroll with code when needed?
