### ISSUE TITLE
[BUG] NotificationsService error when using TuiNotification."status" to define the status

### ISSUE THREAD

**Issue by egbakou** [TinkoffCreditSystems/taiga-ui#495]
# 🐞 Bug report

### Description
I try to define status for a notification using NotificationsService.
When i use TuiNotification.Warning or .Success, i got an error but when i write the status manually as string, no error.

### Reproduction
![](https://i.ibb.co/z66HnDM/Capture-d-cran-2021-06-18-185508.png)

Please, here https://taiga-ui.dev/services/notifications-service, try to edit the Template's section on stackblitz
and click on Withdraw (or Add) to see the error.

### Expected behavior
Error: can't access property "Warning", core_2.TuiNotification is undefined

### Versions

-   Browser [Chrome, Firefox]
-   Angular [12]
-   Package [@taiga-ui/cdk@2.11.1]

**Comment by waterplea** [comment]
Looks like we have to switch to non-const enums:
https://ncjamieson.com/dont-export-const-enums/
StackBlitz does not support them, as some other environments too. If you define a const enum in StackBlitz and console.log it you will see it's an object. If anybody's up to it, it will probably be enough just to drop const for all enums we have.

**Comment by egbakou** [comment]
Okay i see.
It wotks in real project so I thnik we can close this issue.
