### ISSUE TITLE
[BUG] Breadcrumbs dont get populated

### ISSUE THREAD

**Issue by sendoggo** [TinkoffCreditSystems/taiga-ui#557]
# 🐞 Bug report

I can't populate BreadCrumbs dynamically. Trying to populate it through a service that gets the current page URL (`window.location.pathname`) and splits it at each "/". Each element of the outputted array should be an element of the **BC** list. 

If I hardcode a list of objects the BC get populated without any issue

However, I can *ngFor over the list of fetched elements from the service and display them in the template under any other compoment or html element.

```html
<tui-breadcrumbs>
<ng-container *ngFor="let bc of breadcrumbs">
 <a *tuiBreadcrumb tuiLink [routerLink]="bc.routerLink">
{{ bc.caption}}
 </a>
</ng-container>
</tui-breadcrumbs>
````

Here's the service that retrieves the url, splits it and returns an array of Breadcrumbs objects ({ `caption`: string, `routerLink`: string}):

```typescript
getBreadcrumbs(): Observable<Breadcrumb[]> {
    this.ITEMS = []
    this.routerLink = ''
    window.location.pathname.split('/').forEach(element => {
      if (element != '') {
        this.routerLink = this.routerLink.concat(element, '/')
        this.ITEMS.push({
          caption: element,
          routerLink: this.routerLink
        })
      }
    })
    const routes = of(this.ITEMS);
    return routes;
  }
```

I believe there is something wrong with this ngFor within the ng-container related to Taiga. I can *ngFor over the breadcrumbs array outside of it and all the elements are shown correctly (for example, i can display a list of buttons with each element being an element of the array)

### Versions

-   OS: ubuntu
-   Browser firefox
-   Angular 11
-   Package Latest 2.13.0

**Comment by waterplea** [comment]
Hi. Thank you for raising this. I'm currently on vacation, but the fix is very easy, if you want to contribute — you can make a PR. You need to add the following code here:
https://www.github.com/TinkoffCreditSystems/taiga-ui/tree/main/projects%2Fkit%2Fcomponents%2Fbreadcrumbs%2Fbreadcrumbs-wrapper.template.html
```
<ng-container *ngIf="items.changes | async"></ng-container>
```
At the first line of the template. Here's my little article about it:
https://medium.com/angularwave/a-simple-trick-you-need-for-dynamic-contentchildren-6ed0eae49cb4

**Comment by sendoggo** [comment]
Ty, I'm not sure though where this line of code should go.
Guessing it has to go within the Taiga UI somewhere (you added the link), but should that tag wrap around this:

```html
<ng-container *ngFor="let item of items; let last = last">
    <ng-container *ngTemplateOutlet="item"></ng-container>
    <tui-svg *ngIf="!last" class="icon" src="tuiIconChevronRight"></tui-svg>
</ng-container>
```

Be on a different line? Or on the same line as the ngFor? If I'm correct you cant put multiple template bindings on one element

**Comment by waterplea** [comment]
No need to wrap anything, just add it as is at the beginning of the template. It's only needed to trigger change detection.

**Comment by sendoggo** [comment]
I'll give a try,
ty

**Comment by waterplea** [comment]
Thank you :)
