### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by izlom** [TinkoffCreditSystems/taiga-ui#576]
# 🐞 Bug report
Текст внутри кнопки выходит за границы.
![image](https://user-images.githubusercontent.com/14006154/126746264-0bb5937d-0c84-4c15-b7b5-45b455dc3653.png)
https://taiga-ui.dev/components/button/API?tuiMode=null

**Comment by waterplea** [comment]
For some reason `shape` is defaulted to `square` rather than `null` on the demo page. We'll change that in some other PR since this is a very small change. Thank you.
