### ISSUE TITLE
[BUG] Incorrect work card grouped control with autocomplete

### ISSUE THREAD

**Issue by Smirnov906** [TinkoffCreditSystems/taiga-ui#597]
# 🐞 Bug report

### Description

After submit card from browser storage, control looks like untouched
![image](https://user-images.githubusercontent.com/17454497/128157006-9146122b-a20c-48f2-8030-ddb9d2d494e7.png)
![image](https://user-images.githubusercontent.com/17454497/128157029-6aba8392-c43c-41f7-8ab2-74901d2adc08.png)

### Versions

-   OS: [e.g. iOS]
-   Browser chrome
-   Angular 12
-   Package taiga 2.13.1

**Comment by waterplea** [comment]
Fixed by https://github.com/TinkoffCreditSystems/taiga-ui/issues/634
