### ISSUE TITLE
[FEATURE] a lazy loading image inside the Avatar component  

### ISSUE THREAD

**Issue by IKatsuba** [TinkoffCreditSystems/taiga-ui#62]
# 🚀 Feature request

### Is your feature request related to a problem?

 I'm always frustrated when an image is not loading lazily. Like an image inside the Avatar component.

### Describe the solution you'd like

 All images inside the Avatar component loaded lazily OR loaded using the 'loading="lazy"' property

### Describe alternatives you've considered

 Nope

**Comment by waterplea** [comment]
@IKatsuba are you talking about this?
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/kit/directives/lazy-loading/lazy-loading.directive.ts

**Comment by IKatsuba** [comment]
@waterplea but how can I use it with tui-avatar?

**Comment by waterplea** [comment]
Misread. Yeah, I guess we can add this directive to Avatar.

**Comment by waterplea** [comment]
Lighthouse also complains about not setting explicit size for images in avatars. Gotta look into that.
