### ISSUE TITLE
[BUG] `TuiRadioList` breaks when using component as itemContent

### ISSUE THREAD

**Issue by vladimirpotekhin** [TinkoffCreditSystems/taiga-ui#630]
# 🐞 Bug report

### Description

it seems like the component constantly recreating content

### Reproduction

https://stackblitz.com/edit/radio-list-issue

### Versions

version @taiga-ui 2.14.0

**Comment by dolgiyspb** [comment]
Fun fact: this issue appears only in ng12
I could not reproduce it in ng9/10/11
