### ISSUE TITLE
[FEATURE] `InputDateTime` opens calendar with min/max month (if current month less/more)

### ISSUE THREAD

**Issue by nsbarsukov** [TinkoffCreditSystems/taiga-ui#646]
# 🚀 Feature request

### Describe the solution you'd like
If current month is less/more than min/max month in [InputDateTime](https://taiga-ui.dev/components/input-date-time) => make the first opening of calendar with min/max month.

BUT all subsequent click on calendar opens it with last opened month (as it was before).

**Comment by vladimirpotekhin** [comment]
We will also need to think about `null` as the max / min value. Now null breaks the component. Perhaps the default value should be set
