### ISSUE TITLE
[FEATURE] `addon-doc` Long menu items

### ISSUE THREAD

**Issue by vladimirpotekhin** [TinkoffCreditSystems/taiga-ui#648]
# 🚀 Feature request

### Is your feature request related to a problem?

Long menu items don't fit in the side-menu

### Describe the solution you'd like

Perhaps we should show each menu item in one line with elipsis, or make it customizable

### Additional context

![image](https://user-images.githubusercontent.com/46284632/130826624-ae936a90-eb9e-4bd3-aa8e-93c431c856ac.png)

**Comment by yurakhomitsky** [comment]
To implement this feature all we have to do is to introduce the "max-width": 100% property in the tuiLink component and add these styles to the content block

```
white-space: nowrap;
text-overflow: ellipsis;
width: 100%;
overflow: hidden;
vertical-align: top;

```

Let me know if that makes sense to you so I can go ahead and introduce this changes.

**Comment by waterplea** [comment]
Can you add max-width inplace too, not on every tuiLink? I'd like to build in as little styles as possible in those low level components.
