### ISSUE TITLE
[BUG] TuiMobileCalendarDialog doesn't work

### ISSUE THREAD

**Issue by LuckeeDev** [TinkoffCreditSystems/taiga-ui#663]
# 🐞 Bug report

### Description

I tried following [the docs](https://taiga-ui.dev/components/mobile-calendar/Setup), but the mobile calendar dialog doesn't appear when using `InputDate` or `InputDateRange`. The docs state it should work by default, is this not the case? Or am I missing something?

### Reproduction

I have an app with multiple `InputDate`s and `InputDateRange`s. I imported `TuiMobileCalendarDialogModule` in every module of my app, but `InputDate` and `InputDateRange` don't bring up a calendar window on mobile.

### Expected behavior

I expected it to work by default.

### Versions

-   OS: iOS, Android
-   Browser: Chrome, Safari and Brave
-   Angular: 12
-   Package: `@taiga-ui/addon-editor` v2.14.0

**Comment by waterplea** [comment]
It also required `TuiDialogModule` in main module so that there are dialogs in the app (mobile calendar is shown in a dialog). You also can add `TuiMobileCalendarDialogModule` once in main module too. We need to update docs.

**Comment by LuckeeDev** [comment]
@waterplea thank you very much! If you want, I can work on new docs for this.

**Comment by waterplea** [comment]
Yes, that would be great!
