### ISSUE TITLE
[BUG] `addon-doc` "Night mode" label should use pointer cursor to indicate that it's clickable

### ISSUE THREAD

**Issue by hakimio** [TinkoffCreditSystems/taiga-ui#669]
# 🐞 Bug report

### Description

It's possible to toggle "Night mode" state by clicking on "Night mode" label but there is no indication that the label is clickable.

### Expected behavior

Mouse cursor should change to `pointer` when hovering over "Night mode" label to indicate that it's clickable.

**Comment by waterplea** [comment]
Looks like `CheckboxLabeled` and `RadioLabeled` should be changed to pointer too, checked with designers.

**Comment by waterplea** [comment]
Yes, it should behave the same way `CheckboxLabeled` behaves with label shown with pointer. Feel free to contribute if you want to speed it up!
