### ISSUE TITLE
[BUG] `addon-doc` poor CSS property name visibility in dark mode

### ISSUE THREAD

**Issue by hakimio** [TinkoffCreditSystems/taiga-ui#670]
# 🐞 Bug report

### Description

Switch to dark mode in the documentation app and check how CSS style-sheets look like. The property names are quite hard to read.

![image](https://user-images.githubusercontent.com/768105/132004090-4163a43b-ea49-4d30-b721-4ab4896e2e46.png)

### Expected behavior

CSS property names should be readable in dark mode.

**Comment by BharathRavi27** [comment]
Can't this be simply fixed by using `--tui-primary` instead of `--tui-primary-active` for font? 
Any other concerns here?

**Comment by hakimio** [comment]
@BharathRavi27 yes, you could do that or you could also use `--tui-link`, like they use for the CSS selector/class. Anyway, it's a simple fix.
You can find the line which needs to be fixed [here](https://github.com/TinkoffCreditSystems/taiga-ui/blob/b6075d02329f5ba8e16224bc0f69b4a150cb46dc/projects/addon-doc/src/components/main/main.style.less#L144).

**Comment by waterplea** [comment]
My concern is that it would look the same as the class selector. Maybe you can pick a good color from support palette that works for both night and regular modes?
https://taiga-ui.dev/colors/Support_palette

**Comment by BharathRavi27** [comment]
Noticed that this is still open. Created a PR [here](https://github.com/TinkoffCreditSystems/taiga-ui/pull/771)
