### ISSUE TITLE
Question: Globally apply a template to FieldError

### ISSUE THREAD

**Issue by ScottMGerstl** [TinkoffCreditSystems/taiga-ui#708]
Hello, 

My design system calls for an icon to sit next to the error text within FieldError. I see in the documentation that I can supply an ng-template per validator and provide it to a TuiValidationError [per this documentation](https://taiga-ui.dev/components/field-error#patterns). 

However,  is there a way I can globally supply a template?

Here is a visual example of my need:
![image](https://user-images.githubusercontent.com/10718938/133951248-0bba710d-77c8-4c60-9f2f-e6e65814dee1.png)

**Comment by waterplea** [comment]
Hi there! Please use [Discussions](https://github.com/TinkoffCreditSystems/taiga-ui/discussions) for questions.

You can use dynamic component, dependency injection and Proxy object to get something you're after:
https://stackblitz.com/edit/taiga-custom-error
(check out providers in app component)
