### ISSUE TITLE
[BUG] Documentation - Broken link to hosted dropdown

### ISSUE THREAD

**Issue by hakimio** [TinkoffCreditSystems/taiga-ui#737]
# 🐞 Bug report

### Description

The link to `hosted dropdown` in [dropdown directive page](https://taiga-ui.dev/directives/dropdown) leads nowhere.

**Comment by waterplea** [comment]
Yeah, it should be `components` not `directives` in that link, thank you for spotting it. Will you make a PR?

**Comment by hakimio** [comment]
I have opened PR #740
