### ISSUE TITLE
Add support for RTL langueages [FEATURE]

### ISSUE THREAD

**Issue by ZeroGDrive** [TinkoffCreditSystems/taiga-ui#76]
I had a hard time changing the tuiInput from LTR to RTL and I couldn't change the placeholder.

**Comment by MarsiBarsi** [comment]
Hey 👋 
Thank you for your interest in our library!

We'll think about kind of RTL mode for our textfield. Now there is no easy solution :(

Nevertheless, `direction: RTL` works for inputs and you can also try to wrap placeholder content into some block and align it with `text-align: right;`

```
<tui-input ...>
    <div class="content">
        placeholder <strong>strong text</strong>
    </div>
</tui-input>
```

```
.content {
    text-align: right;
}
```

**Comment by mkibaly** [comment]
This is amazing library 💯 
Supporting RTL languages will be great feature 👍

**Comment by waterplea** [comment]
@mkibaly @ZeroGDrive I'm working on supporting text-alight: right for all inputs which would move us closer to RTL languages. I have a question, in RTL languages all icons like hint, cleaner etc are expected on the left side of an input field?

**Comment by ZeroGDrive** [comment]
@waterplea Yeah exactly icons should be in the left side, Thank you for your efforts!

**Comment by waterplea** [comment]
@ZeroGDrive @mkibaly please take a look at last examples on these pages:

https://taiga-ui--pr983-rtl-2l3lbt4w.web.app/components/input
https://taiga-ui--pr983-rtl-2l3lbt4w.web.app/components/input-tag
https://taiga-ui--pr983-rtl-2l3lbt4w.web.app/components/multi-select
https://taiga-ui--pr983-rtl-2l3lbt4w.web.app/components/text-area

Is it working as expected?

**Comment by ZeroGDrive** [comment]
> @ZeroGDrive @mkibaly please take a look at last examples on these pages:
> 
> https://taiga-ui.dev/next/components/input https://taiga-ui.dev/next/components/input-tag https://taiga-ui.dev/next/components/multi-select https://taiga-ui.dev/next/components/text-area
> 
> Is it working as expected?

PERFECT!
