### ISSUE TITLE
[BUG] Bad colors to display in documentation

### ISSUE THREAD

**Issue by splincode** [TinkoffCreditSystems/taiga-ui#787]
# 🐞 Bug report

### Description

I use a dark theme everywhere, but visibility is poor in some places

### Reproduction

https://taiga-ui.dev/components/calendar
![image](https://user-images.githubusercontent.com/12021443/135041196-86f604bf-d94e-4b2a-b37b-77cfbc4ef401.png)

https://stackblitz.com/edit/taiga-starter?file=src%2Fapp%2Fapp.component.html

**Comment by waterplea** [comment]
I believe it's fixed already, colors are more contrast now.
