### ISSUE TITLE
🚀 - `Accordion` support eager content

### ISSUE THREAD

**Issue by rvalitov** [TinkoffCreditSystems/taiga-ui#816]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

I use Accordion and Expand components to show/hide a big search form with search results. I want to use the components to allow the user temporarily show/hide the content (both search form, and search results) so it does not consume space on screen when not needed. However, after the user hides and then opens again the Expand or Accordion, the inner content of the components is reset, i.e. it does not preserve the state, the filled fields of the form and the search results. Everything is reinitialized.

I suspect the cause of this reason is that both of these components use `[*ngIf]` to show/hide the content. And it results in such behavior. In order to preserve the state and contents, the `[hide]` should be used.

Example of my code:
```html
<tui-expand [expanded]="expandedClientSelect">
          <ng-template tuiExpandContent>
            <app-clients-list
              [allowCreate]="true"
              [allowSearch]="true"
              [allowCancel]="false"
              (onSelect)="onClientSelect($event)"
            >
            </app-clients-list>
          </ng-template>
        </tui-expand>
```

It would be great if there would be an option like `[useHide]` that define the behavior of the Expand and Accordion components.

**Comment by waterplea** [comment]
This isn't a bug, it's by design. You can drop `ng-template` from `tui-expand` and it would work the way you want. However it's not possible in `tui-accordion`. This could probably be turned into feature request for Accordion.

**Comment by rvalitov** [comment]
@waterplea thank you for a workaround. Yes, after dropping `ng-template` it seems to work properly. But in the browser console now I get error every time the Expand is closed:
```
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '_focused': 'true'. Current value: 'false'.. Find more at https://angular.io/errors/NG0100
```

Is it something serious?

**Comment by waterplea** [comment]
Not sure, I'll probably need a StackBlitz to dig into this.

**Comment by waterplea** [comment]
For accordion feature we can probably add another directive to put on content that would project it without template directly into the expand.
