### ISSUE TITLE
[BUG] content shakes during animation in TuiActionModule

### ISSUE THREAD

**Issue by aalexeev239** [TinkoffCreditSystems/taiga-ui#90]
# 🐞 Bug report

### Description

Content shakes during animation. Adding `will-change` will fix such behaviour.

### Reproduction

https://taiga-ui.dev/tui-action/Setup 

https://user-images.githubusercontent.com/6787602/104334993-09f1be00-5504-11eb-8b2c-4991ad4354c2.mov

### Versions

-   OS: macOs
-   Browser Google Chrome Version 87.0.4280.141
-   TuiActionModule

**Comment by waterplea** [comment]
@aalexeev239 thanks for spotting and providing a solution! Perhaps you will also be able to make a PR? :)

**Comment by aalexeev239** [comment]
@waterplea ☝️
