### ISSUE TITLE
🐞 - TuiCountryIsoCode.UK must be TuiCountryIsoCode.GB

### ISSUE THREAD

**Issue by rvalitov** [TinkoffCreditSystems/taiga-ui#916]
### Which @taiga-ui/* package(s) are the source of the bug?

i18n

### Description

There's no valid ISO country code `UK` according to the current officially assigned country codes https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
It must be changed to `GB`.

Similar issue #915 

P.S. I can make a PR

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Agree. Let's just change it.
