### ISSUE TITLE
[BUG] Broken icons in InputPhoneInternational

### ISSUE THREAD

**Issue by vdvukhzhilov** [TinkoffCreditSystems/taiga-ui#94]
# 🐞 Bug report

### Description

InputPhoneInternational component page on documentation site has broken pics for icons, representing some countries like Russia, USA. But for some countries icons are not broken.
![image](https://user-images.githubusercontent.com/17381580/104421468-70222380-558c-11eb-98aa-9a27ce615dd4.png)

### Reproduction

1. Go to https://taiga-ui.dev/tui-input-phone-international
2. See broken icons on the right of the input and in select.

### Expected behavior

The icons should be visible

### Versions

-   OS: MacOS Catalina 10.15.7
-   Browser Chrome 87.0.4280.141 (also Safari 14)

**Comment by fynnfeldpausch** [comment]
Seems to be a bug in the icons itself since icons like https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/icons/src/AT.png are at 0kb

**Comment by MarsiBarsi** [comment]
Thank you for your bug report and interest in Taiga!

Fixed in #96
