### ISSUE TITLE
📚 - Menu behavior issues

### ISSUE THREAD

**Issue by splincode** [TinkoffCreditSystems/taiga-ui#968]
### What is the affected URL?

https://taiga-ui.dev/next/dialogs

### Description

https://user-images.githubusercontent.com/12021443/140023935-8031bb99-7ddb-474f-8aff-44368c914d06.mov

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea why closed?

**Comment by waterplea** [comment]
Cause it's fixed )
