### ISSUE TITLE
[FEATURE] InternationalInputPhone i18n 

### ISSUE THREAD

**Issue by MarsiBarsi** [TinkoffCreditSystems/taiga-ui#97]
InternationalInputPhone has a default list of countries with names in Russian. It would be better to have it in Eng with a russian version as an alternative

**Comment by WuglyakBolgoink** [comment]
Hallo @waterplea / @MarsiBarsi 

Is this correct place: https://github.com/TinkoffCreditSystems/taiga-ui/blob/854b544e87a8916703ecdb8624757b602b3e9a40/projects/kit/components/input-phone-international/const/countries.ts ?


I have a full list on DE + EN translations.

possible solution to have a pipe for translations and any global Token for Main Language... What you think?

**Comment by NaveenKumarDudi** [comment]
Is there any workaround/ solution to change the dropdown content into English language ?

**Comment by waterplea** [comment]
@WuglyakBolgoink would you be willing to contribute? We have internationalisation mechanism in place. A single token for Observable and constants for various languages that people can provide. We need to switch from the constant you pointed at to that in input phone. See this:
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/i18n/languages/english/kit.ts

**Comment by WuglyakBolgoink** [comment]
tnx @nsbarsukov for PR

why you choose alpha-2 instead of using alpha-3, which is more popular?...

**Comment by nsbarsukov** [comment]
> why you choose alpha-2 instead of using alpha-3, which is more popular?...

@WuglyakBolgoink 
We have historically used alpha-2 for `InternationalInputPhone`.

In this PR, I've just moved the constant from
`projects/kit/components/input-phone-international/country-iso-code.ts` to `projects/i18n/enums/country-iso-code.ts`
(with maintenance of backward compatibility)

How critical is this? If it is really necessary, then we can mark it as TODO and make it in v3.0.

**Comment by waterplea** [comment]
@WuglyakBolgoink it says here that alpha 2 is the most widely used and is also the base for domain names and postal identifiers:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2?wprov=sfla1
Are you sure about alpha 3 being more popular?

**Comment by WuglyakBolgoink** [comment]
@waterplea  / @nsbarsukov 

this is not a critical.

About popularity... Hm, in all our projects we used always alpha-3 and our clients use this too.

but this is "nice2have" and no necessary to do something more with this feature.
